#!/bin/bash

IPA_SERVERS="""172.16.1.10
172.16.1.11
NONE"""
OUTPUT_FILE=/etc/dhcp/dhcpd.auto.conf

# find the first available ipa server
for ipa_server in $IPA_SERVERS; do
	if [[ $ipa_server == "NONE" ]]; then
		echo 'No IPA Servers found.' >&2
		exit 1
	fi

	echo "trying $ipa_server."
	if dig @$ipa_server +time=1 +tries=1 dhcp. &>/dev/null; then
		break
	fi;
	echo "$ipa_server not reachable."
done;
echo "using $ipa_server."

# clear output tmp file
echo """
# This file has been autogenerated from the records defined in
# the dhcp DNS zone. Please modify these records on the IPA
# servers.
""" > $OUTPUT_FILE.new

# lookup all the host records defined in the dhcp zone
record_names=$(dig axfr @$ipa_server dhcp. +answer | \
	egrep -v '(^;|^$)' | \
	egrep '(IN\s+A\s|IN\s+TXT\s)' | \
	awk '{ print $1 }' | \
	sort -u)

# lookup details for all host records
for record in $record_names; do
	# find first ip address in a record
	ip_addr=$(dig A @$ipa_server $record +noauthority +noadditional | \
		egrep -v '(^;|^$)' | \
		awk '{ print $5 }' | \
		egrep '^([0-9]{1,3}\.){3}([0-9]{1,3})$' | \
		head -n 1)
	# find first mac address in txt record
	mac_addr=$(dig TXT @$ipa_server $record +noauthority +noadditional | \
		egrep -v '(^;|^$)' | \
		tr -d '"' | \
		awk '{ print $5 }' | \
		egrep '^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$' | \
		head -n 1)

	if [ ! -z "$record" ] && [ ! -z $ip_addr ] && [ ! -z $mac_addr ]; then
		echo """
host $record {
  hardware ethernet $mac_addr;
  fixed-address $ip_addr;
}
""" >> $OUTPUT_FILE.new
	fi
done

# check if an update is required
if ! diff $OUTPUT_FILE $OUTPUT_FILE.new &>/dev/null; then
	# update the reservations
	cp $OUTPUT_FILE $OUTPUT_FILE.last
	cp $OUTPUT_FILE.new $OUTPUT_FILE
	if dhcpd -t &> /dev/null; then
		rm $OUTPUT_FILE.new
		systemctl restart dhcpd
		echo "Reservations have been updated."
	else
		echo "Invalid DHCP config file at $OUTPUT_FILE.new" >&2
		exit 2
	fi
else
	echo "No update."
fi

